### ISSUE TITLE
empty file name creates hidden .webm file

### ISSUE THREAD

**Issue by kparal** [green-project/green-recorder#18]
I started a recording and kept the filename field empty. I simply forgot about it, but I instinctively assumed that if I don't fill it in, a reasonable default will be provided (for example something like `screencast-<timestamp>.webm`). Instead, I stopped the recording and no video file appeared. I assumed that it just wasn't created because I didn't specify the filename. Only later I discovered it created a `.web` file, which is hidden by definition (starts with a dot). That's quite non-obvious.

Please use a reasonable default if filename is not provided? Or don't allow to start the recording until a filename is provided. (But the first solution is more user friendly).

green-recorder-2.2-1.fc25.noarch

**Comment by mhsabbagh** [comment]
Actually that's a known "feature". I know some cases where such hidden files can be used for some special stuff. I don't think that the user should be restricted from doing it. You could have known that the recorder is already on since the indicator started to work in the notifications area. Since it didn't stop or show an error, it's definitely working.

**Comment by kparal** [comment]
It was very much unknown to me and I bet it'll be even to 100% of any new user base (because how would they about this?). I could clearly see that the recorder was working, but after stopping it, there was no file in my home directory. And it didn't even occur to me that it would create a `.webm` file.

It would be clearer if there was a regular file-save dialog with ".webm" pre-filled. But the extension is actually a drop-down, and it is a file **format** selection. It's not clear that it also dubs as file name extension selection (especially for no-filename files).

Regarding hidden files. If anyone wants to have their recordings hidden, why couldn't they either rename the file after recording, or name them as `.something.webm`? Who would even want to create a `.webm` file? I'm curious. And if such a person exists, he's clearly an extremely minuscule part of the user base. Why not let the person to handle that himself (or perhaps add a CLI option to specify this, since he's clearly a power-user) and not confuse the majority of general users, who will have no idea about this "feature" and be just confused?

**Comment by kparal** [comment]
In shorter words, the first thing a regular user will do, is to hit the record button. And for them, this tool will appear broken.

**Comment by Sesivany** [comment]
I agree with @kparal here. I stumbled on this as well when I tried the Recorder for the first time. I forgot to write the name. When I finished recording, I looked in the Videos folder and because I didn't find any such video file there, I thought: ok, the recording was probably tossed and never saved. Nevermind. It would never ever occur to me that it's saved as a hidden file. Why?
I would go even that far and say that hidden files is something an average user should not be expected to work with. If there are hidden files in the system, they are hidden for a good reason. This is the first time I see a hidden video file.

**Comment by SafaAlfulaij** [comment]
I would say that the easiest and best way is to display a "notice" icon using some functions of GtkEntry, like [gtk-entry-set-icon-from-stock](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-icon-from-stock ) and [gtk-entry-set-icon-tooltip-text](https://developer.gnome.org/gtk3/stable/GtkEntry.html#gtk-entry-set-icon-tooltip-text).

**Comment by mhsabbagh** [comment]
Yep. Probably I would go with the notice icon or an info message before the recording starts.

**Comment by kparal** [comment]
So why not make it easier and actually generate a name if none is provided? Because honestly I don't care how the file is named, I just want to record a video. If I can simply hit record and it automatically creates a reasonably-named file (timestamp in a name or something), I'll be much happier than if I have to provide some name every single time.

Compare this to hitting a PrintScreen - a reasonably-named screenshot is created in your Pictures folder. Again, simple and expectable behavior.

**Comment by SafaAlfulaij** [comment]
Then maybe another checkbox for enabling auto file-naming and disabling the entry. What do you think, @mhsabbagh ?
But I'm not sure if the app can now save settings and restore them on next start, or not...
