### ISSUE TITLE
No sound !

### ISSUE THREAD

**Issue by nam1962** [green-project/green-recorder#9]
Hi there, this project is appealing, I love the simplicity, but...
..cannot get any sound from my Manjaro install.
My internal mike is ok in pulseaudio, checked on the recording screen, but I only get a silent record (tried in mkv & avi

**Comment by mhsabbagh** [comment]
Hi there. 

Thank you for your interest in this project. Can you please run green-recorder from the command line and attach the output here when u try to record?

**Comment by nam1962** [comment]
Here you are !
`~]$ green-recorder
E: [pulseaudio] pid.c: Daemon already running.
E: [pulseaudio] main.c: Échec de pa_pid_file_create().
aserver aserver.c:1033:(main) you need to specify server name
`

**Comment by mhsabbagh** [comment]
No this is not it. YOu need to record something and then take the output not just directly after you open the program

**Comment by nam1962** [comment]
Ah ok !

[green-recorder-terminal-output.txt](https://github.com/green-project/green-recorder/files/774556/green-recorder-terminal-output.txt)

**Comment by mhsabbagh** [comment]
Ok. Things looks to be working from the program's side. The recorder takes the input sound from the "default" channel (which was also the case from what I see in your log). However, if this default channel was something different than the microphone. You probably will end up not having any sound.

I don't know how things work on Arch or Manjaro. But if you can install pavucontrol (control tool for PulseAudio) and change the default channel to the microphone. It should work with you.

On Ubuntu and Fedora. This is the situation by default which is why I didn't notice it. The Arch package was provided by a 3-rd party so it's not officially built to be "compatible" with Arch or Manjaro.

**Comment by nam1962** [comment]
Waow ! i found the problem, that one was tricky : On pulseaudio, the default was internal mike on my  input tab, BUT, on the recording tab, it was @ "monitor of internal audio" instead of "internal audio".
As this tab only shows the possible setting when one is recording, I missed it !
Thanks for the hint ;)

Additional remark : if I forget to give a title to the file, it is recorded as .mkv (thus considered as a hidden file)
Best !

**Comment by mhsabbagh** [comment]
Glad it worked :)

**Comment by nam1962** [comment]
My first use of it was this : https://dolys.fr/forums/topic/green-recorder-truc-plus-simple-enregistrer-ecran/ ;)
